driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
    - recipe[apt::default]
  - name: ubuntu-12.04
    run_list:
    - recipe[apt::default]
  - name: ubuntu-10.04
    run_list:
    - recipe[apt::default]
  - name: debian-7.7
    run_list:
    - recipe[apt::default]
  - name: debian-6.0.10
    run_list:
    - recipe[apt::default]
  - name: freebsd-9.2
    run_list:
    - recipe[freebsd::portsnap]
  - name: centos-7.0
  - name: centos-6.6
  - name: centos-5.10
  - name: fedora-20
  - name: fedora-21

suites:
 - name: package
   run_list:
   - recipe[nrpe::default]
 - name: source
   run_list:
   - recipe[nrpe::default]
   attributes:
     nrpe:
       install_method: 'source'
 - name: check
   run_list:
   - recipe[chef_nrpe_test::default]
