---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-8.2
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.7
  - name: centos-7.2

suites:
  - name: repo
    run_list:
      - recipe[monit-ng]
      - recipe[setup]
  - name: source
    excludes:
      - ubuntu-12.04
      - centos-6.7
    run_list:
      - recipe[monit-ng]
      - recipe[setup]
    attributes:
      monit:
        install_method: source
